spring:
  application:
    name: chap05-spring-mybatis-lecture-source

# DB ?? ??
datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  # jdbc-url ?? url? ???? ?? ? ?????? (? ? ??? ? ??)
  jdbc-url: jdbc:mariadb://localhost:3306/menudb
  username: swcamp
  password: swcamp